# This is a basic workflow to help you get started with Actions
name: Test & deployement

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
         java-version: '17'
         distribution: 'adopt'

    - name: Construire le projet
      run: mvn clean install 

    - name: Executer les tests
      run: mvn test  # Exécute les tests unitaires

    

    
    

# name: Node.js CD

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#     - name: Deploy using ssh
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USERNAME }}
#         key: ${{ secrets.PRIVATE_KEY }}
#         port: 22
#         script: |
#           cd ~/home/danielwetan/apps/node1
#           git pull origin master
#           git status
#           npm install --only=prod
#           pm2 restart node1